baseURL = "./"
relativeURLs = true

languageCode = "en-us"
defaultContentLanguage = "en"
title = "CV Berest Anastasiia"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#6c95b4"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
